sudo: required
services:
  - docker

before_install:
  - docker build -t peterpan01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true peterpan01/react-test npm test -- --coverage

after_success:
  - docker build -t peterpan01/multi-client ./client
  - docker build -t peterpan01/multi-nginx ./nginx
  - docker build -t peterpan01/multi-api ./api
  - docker build -t peterpan01/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push peterpan01/multi-client
  - docker push peterpan01/multi-nginx
  - docker push peterpan01/multi-api
  - docker push peterpan01/multi-worker

