sudo: required
services:
  - docker

before_install:
  - docker build -t peterpan01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true peterpan01/react-test npm test -- --coverage

after_success:
  - docker build -t peterpan01/multi-client ./client
  - docker build -t peterpan01/multi-nginx ./nginx
  - docker build -t peterpan01/multi-api ./api
  - docker build -t peterpan01/multi-worker ./worker


